Rakefile: A minimum speculative fix for:
martind@swiftboat:~/download/rdbi-driver-odbc.orig$ rake
rake aborted!
ERROR: 'rake/gempackagetask' is obsolete and no longer supported. Use 'rubygems/package_task' instead.
/home/martind/download/rdbi-driver-odbc.orig/Rakefile:30:in `<top (required)>'
(See full trace by running task with --trace)
martind@swiftboat:~/download/rdbi-driver-odbc.orig$